# Sniperkit-Bot
# - Date: 2018-08-11 22:33:29.968253967 +0200 CEST m=+0.111794099
# - Status: analyzed

version: "3.5"
services:
  dbnode01:
    expose:
      - "9000-9004"
    ports:
      - "0.0.0.0:9000-9004:9000-9004"
      - "0.0.0.0:2379-2380:2379-2380"
    networks:
      - backend
    build:
      context: .
      dockerfile: ./docker/m3dbnode/Dockerfile
    image: m3dbnode01:latest
    volumes:
      - "~/m3db:/var/lib/m3db"
  coordinator01:
    expose:
      - "7201"
    ports:
      - "0.0.0.0:7201:7201"
    networks:
      - backend
    build:
      context: .
      dockerfile: ./docker/m3coordinator/Dockerfile
    image: m3coordinator01:latest
networks:
  backend:
