# Sniperkit-Bot
# - Date: 2018-08-11 22:33:29.968253967 +0200 CEST m=+0.111794099
# - Status: analyzed

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "30"
